### ISSUE TITLE
有几个视频都无法合成，可能是文件名太长了？

### ISSUE THREAD

**Issue by ReDiracte** [2niuhe/jable_downloader#6]
开始合成视频...
Traceback (most recent call last):
  File "Z:\jable_downloader-main\jable_downloader-main\main.py", line 36, in <module>
    args.func(args)
  File "Z:\jable_downloader-main\jable_downloader-main\executor.py", line 110, in process_subscription
    video_crawler.download_by_video_url(download_url)
  File "Z:\jable_downloader-main\jable_downloader-main\video_crawler.py", line 155, in download_by_video_url
    merge_mp4(tmp_dir_name, output_dir, video_full_name, ts_list)
  File "Z:\jable_downloader-main\jable_downloader-main\utils.py", line 112, in merge_mp4
    with open(os.path.join(output_path, video_name + '.mp4'), 'ab') as f2:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'Z:\\jable_downloader-main\\jable_downloader-main\\DVDMS-493 催 ●術でご近所の巨乳妻を90日間にわたってオーガズム洗脳 2 乳首イキ/喉奥イラマイキ/脳イキを繰り返しのけぞり絶頂した寝取られ 妻は自ら子宮に中出しを求める 三原穗香.mp4'

**Comment by 2niuhe** [comment]
因为视频标题中存在字符/，没法创建文件。这个问题已经修复了，可以下载最新版使用。

**Comment by ReDiracte** [comment]
好的，谢谢！

**Comment by ReDiracte** [comment]
OSError: [Errno 22] Invalid argument: 'Z:\\jable_downloader-main\\jable_downloader-main\\DASD-692 這是一段錯過彼此的淒美回憶可愛的學生會長久留木玲催眠無效反而被劇烈抽插\t 久留木玲.mp4'

我试了最新的，还是不行，你代码里的是/，cmd里显示的是\，不知道是不是这个问题

**Comment by 2niuhe** [comment]
哦哦，是这个问题，window上文件路径用\来分割的，我只处理了Linux上的情况。我有时间修复一下。

**Comment by 2niuhe** [comment]
@ReDiracte 
问题应该已经修复了
