### ISSUE TITLE
有视频无法合成，没看出来什么端倪

### ISSUE THREAD

**Issue by ReDiracte** [2niuhe/jable_downloader#7]
开始合成视频...
Traceback (most recent call last):
  File "Z:\jable_downloader-main\jable_downloader-main\main.py", line 36, in <module>
    args.func(args)
  File "Z:\jable_downloader-main\jable_downloader-main\executor.py", line 110, in process_subscription
    video_crawler.download_by_video_url(download_url)
  File "Z:\jable_downloader-main\jable_downloader-main\video_crawler.py", line 161, in download_by_video_url
    merge_mp4(tmp_dir_name, output_dir, video_full_name, ts_list)
  File "Z:\jable_downloader-main\jable_downloader-main\utils.py", line 112, in merge_mp4
    with open(os.path.join(output_path, video_name + '.mp4'), 'ab') as f2:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'Z:\\jable_downloader-main\\jable_downloader-main\\GMEM-015 狂気拷問処刑 Episode02:悪魔の媚薬に暴かれし神秘の肉体 悲愴！逝き晒し処刑 孤高の女捜査官 奏自由.mp4'

**Comment by 2niuhe** [comment]
应该还是文件名特殊字符的问题，怀疑是冒号或者感叹号，我后面修复一下。
